name: Deploy Portfolio Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.100
      # Publish the site
      - name: Publish
        run: |
              cd GraphVisualizer
              dotnet publish GraphVisualizer.csproj -p:GHPages=true -c:Release -o:publish

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./GraphVisualizer/publish/wwwroot/
          force_orphan: true
